name: Deploy to netlify on merge
on:
  push:
    branches:
      - main # 要監聽的分支

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        # flutter-version: '3.3.10' # 你使用的Flutter版本
        channel: "stable"

    - name: Install dependencies
      run: flutter pub get
        
    - name: Build Web
      run: flutter build web
        
    - name: Deploy to Netlify
      uses: nwtgck/actions-netlify@v2
      with:
        publish-dir: './build/web' # 要部署的目錄
        github-token: ${{ secrets.GITHUB_TOKEN }} # 會自動添加
        netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }} # 需要在GitHub Secrets中設置
        netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }} # 需要在GitHub Secrets中設置
